### ISSUE TITLE
Website search doesn't seem to work

### ISSUE THREAD

**Issue by yugaego** [fish-shell/fish-site#111]
Hi. *Each* search request I try, including [`for` query](https://github.com/fish-shell/fish-shell/issues/7757), outputs *only* the following message:

> Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.

I'm on the latest MacOS Safari desktop with JS enabled, if that's of any help checking the issue.  
URL: https://fishshell.com/docs/current/search.html?q=for

**Comment by faho** [comment]
First of all, from the README:

> Contributions to fish shell documentation are very welcome. However, the contents of the docs in particular are derived from the [fish-shell](https://github.com/fish-shell/fish-shell/) repository. Please direct pull requests concerned with fish shell documentation to that repo (see the doc_src directory).

These issues are really just for the main site itself, not the documentation.

Secondly, unfortunately `for` is too short for sphinx' search to find anything and we can't really do anything about it. Sorry.
