### ISSUE TITLE
What happened to the main page of fishshell.com ?

### ISSUE THREAD

**Issue by mikelei8291** [fish-shell/fish-site#114]
The new color looks very weird to me and the contrast is just too high. I know high contrast mode is a thing but not everyone needs that.

Also in my opinion the comic sans font is just not suitable for a piece of software that interacts with your computer.

Is this some kind of out of the season April fools joke?

**Comment by faho** [comment]
We're doing a bit of a joke, yeah. I think we'll keep it for a bit and then return to the previous state.

**Comment by mikelei8291** [comment]
@faho Could you please explain a bit on what the joke is about? I haven't followed the development of fish for some time and I'm confused about this change.

**Comment by faho** [comment]
It's pink and uses Comic Sans. That's entirely unprofessional, which is funny to do on purpose.

**Comment by simonfelding** [comment]
@faho don't change it back, it's great
