### ISSUE TITLE
Improve fallback fonts using ModernFontStacks

### ISSUE THREAD

**Issue by fimion** [fish-shell/fish-site#116]
The current comic sans look fails to be effective on mobile devices (including android) and could easily be improved by adding some additional fallback font options from [modern font stacks](https://modernfontstacks.com/)

```css
font-family: "Comic Sans MS", "Comic Sans", "Comic Mono", "ComicShannsMono Nerd Font Propo", 'Segoe Print', 'Bradley Hand', Chilanka, TSCu_Comic, casual, cursive;
```
This will be more effective across multiple devices.

Sincerely,

A handwritten font connoiseur

**Comment by faho** [comment]
Thanks, I've taken the specific fonts, but I don't think "cursive" is a good idea, because some fonts that fall under that are much heavier on the "this is hand-written text" idea than we're going for.

(all joking aside, the site should generally be *readable*)
