### ISSUE TITLE
Regarding the magenta home page.

### ISSUE THREAD

**Issue by p7r0x7** [fish-shell/fish-site#117]
The Comic Sans has genuine poetic value, but the magenta backdrop literally hurts my eyes; please consider changing it.

PS Love the other edits!

**Comment by krobelus** [comment]
Yeah I think the magenta doesn't work well with the white and light blue content. Also the title box background looks weird.
@faho can we revert to the old theme until the new one is complete?

**Comment by ridiculousfish** [comment]
I need to publish the site for 3.6.4 - there's some docs issues but I ought to be able to get to it tonight.

**Comment by faho** [comment]
That's fine. I have a branch I still want to merge on my old laptop, but I can't get to it right now.

**Comment by krobelus** [comment]
Should be fixed now. I found that the new theme looks good in dark mode so I tried to preserve that. Thanks

**Comment by p7r0x7** [comment]
I was in dark mode when I said it hurt my eyes /shrug

**Comment by krobelus** [comment]
ok I've reverted all color-related commits

**Comment by p7r0x7** [comment]
Thanks!
