### ISSUE TITLE
Bad download links for Debian, Fedora, and Gentoo

### ISSUE THREAD

**Issue by ProgVal** [fish-shell/fish-site#20]
Download links to [Debian, Fedora, OpenSUSE, and Gentoo](https://github.com/fish-shell/fish-site/blob/master/site/index.html#L198,L220) all target OpenSUSE's website.

**Comment by xfix** [comment]
Gentoo shouldn't point here (I'm on mobile so I really cannot check). As for Debian and Fedora, it's because fish shell repository is indeed hosted on openSUSE servers.

**Comment by zanchey** [comment]
Gentoo doesn't, and the other platforms point to the right place. The openSUSE page is a landing page that allows you to select your distribution as the repositories are all hosted on the Open Build Service.
