### ISSUE TITLE
Possible error in user documentation

### ISSUE THREAD

**Issue by nitishch** [fish-shell/fish-site#22]
In **Escaping characters** section of [this site](http://fishshell.com/docs/current/index.html), it's written *'\t' escapes the tab character*. Is it correct? Shouldn't it be *Escape sequence, '\t', represents the tab character*?  Same problem for many other escape sequences.

**Comment by ridiculousfish** [comment]
You're right, that's better wording. If you want to charge ahead, you can do a PR in the main repo http://github.com/fish-shell/fish-shell/ where the docs are stored.

**Comment by zanchey** [comment]
Fixed with fish-shell@b057efdb37a931633b.
