### ISSUE TITLE
Website enhancements

### ISSUE THREAD

**Issue by marcker** [fish-shell/fish-site#27]
Hi,

I'm a developer front-end  working at [F.biz](http://www.fbiz.com.br/en-us/) and started making some improvements in HTML, CSS and JS.

I'd love to contribute to the project in other ways too, since I use it every day at work and at home. A while ago I made the logo of the [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish) (may know it).

I intend to leave the aesthetics of the site as it is (roots!), however, add compatible with smaller screens, improved HTML, CSS and JS (all assets) with development standards.

I started work on a [new branch](https://github.com/marcker/fish-site/tree/css-enhancements) and may already test -- jumbotron (cool name :sparkles:!) It is already responsive.

What do you think?

**Comment by ridiculousfish** [comment]
Sounds great :+1: I designed and implemented what's there now, but my front-end skills are from the late 90s, hah.

**Comment by marcker** [comment]
:tv: 90's :radio: is great!

I don't think the ugly or bad site (usability), but in small screens is terrible. So I would help.

Let the easiest source also modularizing everything. I will work and if accept my pull request will be grateful to help. If not, OK too.

**Comment by ridiculousfish** [comment]
While we're on the topic, an occasional request is that it not require JavaScript, and I'm a little sheepish that it does (but only a little). JS is used for switching among the OS tabs, which is a little nicer than just throwing everything at you at once ([example](https://mosh.mit.edu)). That said, it would be great if it gracefully degraded so it was usable without JS. Maybe you have some ideas how that could be done.

**Comment by marcker** [comment]
You have little reason to be ashamed about your JS, hahaha.

On the tabs, we are left with the options:

tabs with OS detection via JS or other structure (with all the options set out at once, but elegantly). I prefer the first option yet.

**Comment by ridiculousfish** [comment]
My hope was that when JS is enabled, you get tabs, but if JS is disabled you see all tab content at once. Maybe this can be accomplished by using JS to hide the inappropriate tabs. No JS = all tabs visible.

**Comment by marcker** [comment]
Oh yeah, It will be simple to perform. Let's put into practice.

**Comment by zanchey** [comment]
I'm closing this for now - we'll happily take enhancements of course but I don't think this needs to stay open.
