### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-site#3]
fishshell.com should have a favicon.

**Comment by zanchey** [comment]
Maybe pull the icon from fish-shell/fish-shell@4b8febd44e0e6949?

**Comment by floam** [comment]
I tried my hand at making a better fish icon that works at multiple sizes. The problem with the current icon tended to be the ASCII art had too much density to actually every be recognizable as the beautiful fish that it is, and the cockeyed terminal is weird. So I a couple weeks ago one afternoon I just drew a Standard Terminal Box Like People Do For Icons, and went with a multicolored `<><`.

<img width="631" alt="should-have-this-gradient-oops-oldscreenshot" src="https://cloud.githubusercontent.com/assets/291142/14933342/7fafed80-0e3f-11e6-8d50-1f7465b1efc3.png">

The general idea is that an icon should be scalable - not literally like an SVG (although I have SVG exports), but that it can have variants that are tiny favicons and also huge 512x512 sizes that are consistent in style.  Llarger renderings of the icon should show the `<><` as a smallish feature in the top left of that terminal, while smaller sized renderings the fish takes up a larger proportion of the space. So here is an example of old-timey 16x16 favicon, a 32x32 favicon,  and a 96x96 example of what you might expect to see on a fish.app or something were it used there.

![16](https://cloud.githubusercontent.com/assets/291142/14933234/1ec7a500-0e3d-11e6-8b29-124176ebd421.gif)

![32](https://cloud.githubusercontent.com/assets/291142/14933334/6b7f17dc-0e3f-11e6-922c-ee2acc57d065.png)

![96](https://cloud.githubusercontent.com/assets/291142/14933306/d0415f50-0e3e-11e6-9aa3-363001d77175.png)

**Comment by krader1961** [comment]
I like it. My question is whether we want a warm palette or a cooler palette (blue, blue-green). On the one hand lakes, oceans, etc. tend to be portrayed in cool colors. On the other many beautiful fish tend to have warm colors (e.g., [Koi](https://www.google.com/search?q=koi+fish&tbm=isch&tbo=u&source=univ&sa=X)). So I'm inclined to recommend sticking with your color scheme or something like it.

**Comment by floam** [comment]
I had tried a version where I did cyan, magenta, yellow, and I liked it a bit more. I seem to have not saved it. There may be a .PNG floating around on gitter.

The colors i picked are oddly similar to the sorin theme.

**Comment by floam** [comment]
The acorn files I was working with are posted to [https://drive.google.com/open?id=0B9nS3wSv15QjcXRrZlQweW1FVEU](Google Drive), as well as a bunch of random detritus I had produced around the same time. Unfortunately I used a proprietary editor I like to make it. There are SVG exports I tried there, and PDFs, but they seem to lack the gridlines. They likely have the correct geometry.

**Comment by floam** [comment]
Also, be aware that "have a favicon" is a bit naive: in my experience you need a LOT of icons If you want it to look good (or look like anything at all) in most situations.I recently was quite happy with this solution:: https://gist.github.com/davidhund/332316f82440ef4377f3

**Comment by zanchey** [comment]
This is awesome!

**Comment by mqudsi** [comment]
@ridiculousfish your own avatar looks great at 16px ;)

**Comment by micck** [comment]
As I am using the documentation on the Fish Shell website very extensibly at the moment, I'm always irritated, that it still has no _favicon.ico_ ;)

I did some quick'n'dirty conversions of the Ridiculous Fish symbol: "![fish-ridiculous-16x16](https://user-images.githubusercontent.com/2911922/32419368-1b7ccb36-c279-11e7-80fb-2a591251112a.png)" and the ASCII_Fish: "![fish-ascii-16x16](https://user-images.githubusercontent.com/2911922/32419390-747e399a-c279-11e7-9ffc-0fac8c444ee7.png)" from the webpage. Both are included in the Windows icon format as well as SVG in the attached ZIP file. Feel free to use.

Take care,
Mick

Attachment: [favicons-4-fish-shell.zip](https://github.com/fish-shell/fish-site/files/1444468/favicons-4-fish-shell.zip)

**Comment by zanchey** [comment]
Fixed with #87.
