### ISSUE TITLE
Home page broken

### ISSUE THREAD

**Issue by fibo** [fish-shell/fish-site#32]
I was looking at a video tutorial an noticed a config/fish or something, so I remembered about fish and I really liked the autocompletion suggestion feature but, after searching it on google I find the home page of the site which is broken.

In summary, if I do

```
GET http://fishshell.com/
```

result is

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2D5A40070D8E3EB0</RequestId>
<HostId>
2/aWeIxZaO/t3xjYs5vJSeYityat3f0lt4z3vaLfivgCW8F0w/g2qAnbeMRXUctN
</HostId>
</Error>
```

**Comment by ridiculousfish** [comment]
Blech, I'm trying to add https support and managed to bork the DNS. It should be fixed now - give it a try?

**Comment by fibo** [comment]
Yes, it's the first time I see the fish hp and it is really cool.
I am just arriving at my job place and today I'll try fish-shell. I guess there is some brew formula already, if yes I will pr to update the Readme.

Thnx
