### ISSUE TITLE
Python 3 compatibility for htmlize_relnotes.py

### ISSUE THREAD

**Issue by egorsmkv** [fish-shell/fish-site#38]
Can I update the script for the Python 3?

**Comment by floam** [comment]
This looks trivial - `2to3` handles that script fine and has no problem doing it successfully and it continues to work fine on python 2.7.

**Comment by faho** [comment]
Ideally this would be 2 _and_ 3 compatible, like our other python scripts, which it currently isn't. At the very least there's a keyword `print` call.

**Comment by krader1961** [comment]
I agree with @faho. At this juncture all our python scripts should be compatible with py2.7 and py3. The `print` statement should be handled by `from __future__ import print_function` and converted to the `print()` form. Last time I looked at our scripts I didn't see anything that could not be made to work with either python version with a modest amount of work.

**Comment by floam** [comment]
Fixed in https://github.com/fish-shell/fish-site/commit/cb8e7cb15c1ddebb97d04e2d11996965f69f2b99
