### ISSUE TITLE
Add instructions for Fedora 24

### ISSUE THREAD

**Issue by emersion** [fish-shell/fish-site#42]
Running `dnf install fish` works out of the box.

**Comment by zanchey** [comment]
Wow, we let this languish.

I think we're going to leave the download links pointed at the openSUSE build service for Fedora, as that allows you to install the latest version of fish released. As I understand it, Fedora won't update the package between releases, but please speak up if I'm wrong.

**Comment by zanchey** [comment]
(See #16)
