### ISSUE TITLE
Change website header/title

### ISSUE THREAD

**Issue by flipflop97** [fish-shell/fish-site#44]
"Finally, a command line shell for the 90s"
The 90s? It's 2016.

**Comment by faho** [comment]
This is quite intentional. It's a joke, and we're not gonna change it.

**Comment by gerrywastaken** [comment]
@faho I didn't get the joke and it stopped me from trying fish for probably more than a decade. It was the first thing I read and I just assumed the site and likely the project hadn't been updated for a long time. I think this might actually be the first impression you are sending to most people. Even now as a VERY happy fish user... I'm still not sure I get the joke.

Is this a jab at POSIX? If so I doubt the joke is coming across as you intended it. I suspect a lot more people would use fish if that wasn't their first introduction to it.

**Comment by faho** [comment]
The joke here is that other shells are *even more outdated*. It's half snark, half self-depreciation.

If that really stops you from, you know, scrolling down a page to see the release dates, that's unfortunate.

We like it and we're not changing it.

**Comment by gerrywastaken** [comment]
@faho fair enough and thanks for explaining.

My comment only risked making me look foolish due to those ten years, but I thought it was worth sharing anyway as I love what you have created. I suspect fish would be more popular than __other shells__ if more people had tried it.
