### ISSUE TITLE
scripting.png image is confusing

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-site#46]
The example at *assets/img/screenshots/scripting.png* should be updated to be clearer. See https://github.com/fish-shell/fish-shell/issues/3832 for an example of how that image confused a user.

**Comment by krader1961** [comment]
It would probably be sufficient to begin the example with `cd ~/.config/fish/functions` to make it clear that the script containing the function is expected to be in the users function autoload directory.

**Comment by ridiculousfish** [comment]
I think I want to make this into a function rather than a call to cat.

**Comment by krader1961** [comment]
Presumably by "make this into a function rather than a call to cat" you mean to replace the `cat detect_os.fish` with something like `function detect_os...end`. That is, show how to interactively define such a function. But if we're going to do that it might be better to change the example implementation to something that better illustrates how fish differs from bash, et. al., when expanding vars rather than focusing on a function definition.

**Comment by ridiculousfish** [comment]
I'd love to show how the quoting nonsense isn't necessary, but I'm not sure how best to do that with a screenshot. Anyways I'm game - do you have an idea for what to show?

**Comment by faho** [comment]
Fixed by 456a04f69d502a3bb2205eb7dba363e1c066cf3d.

**Comment by krader1961** [comment]
Thanks, @faho. Your rewrite neatly sidesteps the issues that were confusing our newest member of the fish community.

**Comment by faho** [comment]
Look again - @ridiculousfish made that 😆.

**Comment by ridiculousfish** [comment]
Happy it's krader approved 👍
