### ISSUE TITLE
Legacy HTTP and git:// URLs being used

### ISSUE THREAD

**Issue by ypid** [fish-shell/fish-site#47]
HTTP and ["The Git Protocol"](https://git-scm.com/book/tr/v2/Git-on-the-Server-The-Protocols) are unauthenticated and should not be used anymore. Please update the following:

* Org URL: https://github.com/fish-shell "http://fishshell.com/" → "https://fishshell.com/"
* Repo description URL: https://github.com/fish-shell/fish-shell "http://fishshell.com/"
* Git clone URL: https://fishshell.com/ "git clone git://github.com/fish-shell/fish-shell.git" → "git clone https://github.com/fish-shell/fish-shell.git"

And consider doing a global replace for those URLs in the git repos to catch all legacy occurrences.

**Comment by zanchey** [comment]
Seems sensible.

**Comment by ridiculousfish** [comment]
I'm unclear on the nature of encryption in the git protocol. I thought that GitHub git:// URLs went over SSL. Is that not the case?

**Comment by ypid** [comment]
> Is that not the case?

No, that is not the case. That is why GitHub deprecated its use. Ref: https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by zanchey** [comment]
This will be fixed with the next website deployment.

**Comment by ypid** [comment]
👍 Thanks! Does the website deploy also update the Org URL: https://github.com/fish-shell "http://fishshell.com/" → "https://fishshell.com/" :) ?

**Comment by zanchey** [comment]
No. That will need to be done manually by @ridiculousfish in the organisation settings.

**Comment by ridiculousfish** [comment]
Updated URL and redeployed site - thanks
