### ISSUE TITLE
Multiple FAQs

### ISSUE THREAD

**Issue by dideler** [fish-shell/fish-site#5]
There's a FAQ at http://fishshell.com/docs/2.0/faq.html and http://ridiculousfish.com/shell/faq.html. Most of the content they cover also differs.

I suggest adding the content from the ridiculousfish.com FAQ to the fishshell.com FAQ, and then redirecting (or at least point) the ridiculousfish.com FAQ to the fishshell.com FAQ so you don't have to double your efforts maintaining both.

I can move the content over and send a pull request, I just need to know if I should be editing `docs/current` or `docs/2.0`.

**Comment by zanchey** [comment]
Long since done
