### ISSUE TITLE
use fish.sh as main domain?

### ISSUE THREAD

**Issue by noformnocontent** [fish-shell/fish-site#50]
`fish.sh` seems way more funk'y than `fishshell.com`

**Comment by krader1961** [comment]
What are you proposing? They're both valid and provide the same content.

**Comment by floam** [comment]
He's proposing making fish.sh the primary one we link to. From a marketing perspective, I'm inclined to agree it's superficially superior. I'd go so far as to suggest making fishshell.com do a 301 redirect to fish.sh in the hope that facilitates others using it and that it transfers over the Google-fu.

**Comment by ridiculousfish** [comment]
Mostly it's a pain in the butt to change - have to update the documentation links in the shell, etc.

**Comment by noformnocontent** [comment]
noted that `fish.sh` does not have separate SSL cert and simply shares one with `fishshell.com`

**Comment by zanchey** [comment]
This looks like an extremely bikesheddable change, so I will put my two cents in and say I don't think we should bother, but I recognise the entirely cosmetic nature.

**Comment by floam** [comment]
That should be resolvable - we could get a free SSL cert from https://www.startcomca.com or use Lets Encrypt.

**Comment by mqudsi** [comment]
@noformnocontent that's kind of a big deal. https://fish.sh/ leads to a security warning and does not load by default in a modern browser.

**Comment by ridiculousfish** [comment]
Yikes, I should be able to fix the SSL cert for fish.sh. Thanks for pointing that out.

**Comment by oranja** [comment]
You should be aware of WoSign/StartCom/StartSSL. Some of the certificates they issued in the past were dangerously flawed and both Google and Mozilla's browsers stop trusting the CA.

**Comment by floam** [comment]
Ah, I wasn't aware they were problematic. I used StartSSL a few years ago for a free SSL cert for my own domain but haven't used them recently. Thanks.

**Comment by noformnocontent** [comment]
why not just use `Let's Encrypt`?

**Comment by ridiculousfish** [comment]
fishshell.com is hosted on AWS S3 and uses CloudFront for https, with AWS issued certs.

**Comment by ridiculousfish** [comment]
fish.sh certs should be sorted, thanks for reporting that.

**Comment by faho** [comment]
@ridiculousfish, @fish-shell/contributors: Do we want this?

**Comment by zanchey** [comment]
I don't think so, but this is a bikesheddable question.

**Comment by ridiculousfish** [comment]
I don't really care either way, there's other things I'd rather do.

**Comment by zanchey** [comment]
OK, it sounds there's nobody particularly keen on this change. Thanks for bringing it up though!
