### ISSUE TITLE
Use http://code.jquery.com instead of googleapis.com

### ISSUE THREAD

**Issue by paulvi** [fish-shell/fish-site#58]
http://fishshell.com/#get_fish_windows (swithc to any download tab) is not working for users in China,
where all google*.com service are not working.

Use http://code.jquery.com instead of googleapis.com  
similar to https://github.com/apache/struts-site/pull/46

**Comment by ridiculousfish** [comment]
Thanks. We can probably just drop jquery entirely.

**Comment by ridiculousfish** [comment]
Dropping jQuery is a little harder than I thought since it's tied in with bootstrap, which we don't really use.

**Comment by paulvi** [comment]
jQuery will stay forever. It is used also in Angular.

This issue was about googleapis.com not available in China.

Now when #58 is merged, I (and other users in China without VPN) can download fishshel.

**Comment by paulvi** [comment]
At least one can see content, see #60
