### ISSUE TITLE
install on Windows (continued)

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-site#63]
Because the [orginal iusse #60](https://github.com/fish-shell/fish-site/issues/60) is closed:

Maybe this will help you:
I am using Windows 7 and 7zip.exe for extracting.

```
Download
  https://github.com/git-for-windows/git/releases/download/v2.16.2.windows.1/Git-2.16.2-64-bit.exe
and install it for example under c:\git

Download
   http://repo.msys2.org/msys/x86_64/fish-2.7.1-2-x86_64.pkg.tar.xz
and extract to a temporary directory for example c:\temp
   xcopy /s c:\temp\etc\*  c:\git\etc\
   xcopy /s c:\temp\usr\*  c:\git\usr\

Download
   http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-3-x86_64.pkg.tar.xz
and extract to a temporary directory for example c:\temp
   xcopy /s c:\temp\usr\*  c:\git\usr\

Download
   http://repo.msys2.org/msys/x86_64/bc-1.07.1-1-x86_64.pkg.tar.xz
and extract to a temporary directory for example c:\temp
   xcopy /s c:\temp\usr\*  c:\git\usr\
```

Usage:
```
c:\git\bin\bash.exe -c fish
c:\git\bin\bash.exe -c "fish script.fish"
```

**Comment by billbisco** [comment]
Hi Ghost, I'm very interested in using FISH for Git Bash as well.  Can you be more descriptive of what you do when you finish downloading the files?  Am I supposed to replace them somehow manually?

I really would like to know how to use FISH for GitBash!  It would make my workgroup's life much easier!

**Comment by faho** [comment]
Sorry, I don't think this route is something we wish to support officially.

**Comment by MoonLightElf** [comment]
I recommend this question and answer.  Then install fish via PacMan in msys2.
[https://stackoverflow.com/questions/32712133/package-management-in-git-for-windows/60611888#60611888](url)
