### ISSUE TITLE
The Guix package URL is broken

### ISSUE THREAD

**Issue by co-dan** [fish-shell/fish-site#70]
The current Guix package URL is 404'd.

Perhaps it is possible to replace it with a link to:
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/shells.scm?id=v0.16.0-126-g95ae013092#n88

Albeit this link points only to a specific version of the package and thus has to be updated periodically.
Alternatively you can perhaps link to <https://www.gnu.org/software/guix/packages/F/>?

**Comment by floam** [comment]
I think if they can't offer a permalink with something meaningful to land at, it might make more sense just to link to the homepage and trust people will know how to install it (we show the command to install it).

**Comment by floam** [comment]
I've spoken to to some Guix people on IRC. They have a suggestion which looks like roughly what I would have expected the GNU site to have:

> \<civodul\> floam: ok, makes sense; you could link to https://guix-hpc.bordeaux.inria.fr/package/fish for the time being
> \<floam\>	civodul, that looks like the kind of thing I'd expect to be able to land at! How does that site relate to what I assume is the official one?
> \<jonsger\> floam: GuixHPC is kind of an official "side" project of Guix

**Comment by ammgws** [comment]
Looks like this was fixed in 2032b830da6b137c3c560e3966ed5ca08d81f61e
