### ISSUE TITLE
Possibly a typo in docs

### ISSUE THREAD

**Issue by curusarn** [fish-shell/fish-site#80]
https://github.com/fish-shell/fish-site/blob/2032b830da6b137c3c560e3966ed5ca08d81f61e/site/docs/current/design.html#L53

Is "psub shellscript function" -> "sub shellscript function" a typo?

**Comment by ridiculousfish** [comment]
The correct function is indeed `psub` - [see this](https://fishshell.com/docs/current/commands.html#psub). Thanks for filing anyways!

**Comment by curusarn** [comment]
Oh, my bad.
