### ISSUE TITLE
typos in urls

### ISSUE THREAD

**Issue by butuzov** [fish-shell/fish-site#81]
There are few URLs mistyped in documentation (almost all versions).

1) index.html points to `bind.html#special-case-escape` , correct `commands.html#bind`
2) index.html points to `fish_mode_prompt.html`, correct `commands.html#fish_mode_prompt`
2) commands.html points to `argparse-local-variables`, correct `#argparse`

**Comment by faho** [comment]
These are issues in the documentation source, which is kept in fish fish-shell/ repo and has been changed quite a bit, including a switch-over to sphinx (from doxygen), which changes the link syntax.
