### ISSUE TITLE
Can't search for commands like "if" and "for"

### ISSUE THREAD

**Issue by mikelward** [fish-shell/fish-site#97]
If I search for "for" using the left-side search box on https://fishshell.com/docs/current/index.html, it takes me to https://fishshell.com/docs/current/search.html?q=for&check_keywords=yes&area=default, which says

> Your search did not match any documents.

It would be super helpful if all fish commands were searchable.

Commands that seem broken:

- if
- for
- cd
- and
- or

Commands that are <= 3 chars that seem to work:

- end
- set (albeit suboptimal search ranking)

Is it possible Sphinx has the ones that don't work as stopwords?

**Comment by faho** [comment]
>Contributions to fish shell documentation are very welcome. However, the contents of the docs in particular are derived from the fish-shell repository. Please direct pull requests concerned with fish shell documentation to that repo (see the doc_src directory).

Please open an issue in fish-shell/fish-shell.
